# Copyright (c) 2017 Dustin Doloff
# Licensed under Apache License v2.0

java_library(
    name = "mockito",
    exports = [
        "@net_bytebuddy_byte_buddy//jar",
        "@net_bytebuddy_byte_buddy_agent//jar",
        "@org_mockito_mockito_core//jar",
        "@org_objenesis_objenesis//jar",
    ],
    visibility = [ "//visibility:public" ],
)