env:
    - BAZEL_VERSION='0.5.4'

dist: trusty

sudo: required

before_install:
    - ./travis/before_install.sh

script:
    - bazel build //...
    - bazel test //...

deploy:
    provider: script
    script: bazel run //rsvp:deploy_save_rsvp
    on:
        branch: travis
